spring.application.name=streaming

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/streaming_db
spring.r2dbc.username=postgres
spring.r2dbc.password=123

# Inicializaci�n autom�tica del esquema (opcional si usas docker-entrypoint)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.r2dbc.pool.enabled=true
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG


whatsapp.base-url=https://graph.facebook.com
whatsapp.api-version=v19.0
whatsapp.phone-number-id=1093748073803306
whatsapp.access-token=EAAMip0boAzYBQz032o3LUzv59yYZARzrF5sZBnQvaOVx1ST7cmbkKs0wf1stnTeBPYRXNfPISTQpOaUJAt3fsOSJdEpLXyjFFZCbpufHQAHSnIfn83CeNF7qp475yyfbpuMjjEnn5YVppLMbd3BVB5KCIRP078plBQGZB5g6cvkV7Lxnvs0A98RxfLx4ELsztQZDZD
whatsapp.template-name=streaming_notif
whatsapp.language-code=es
