spring.application.name=streaming

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/streaming_db
spring.r2dbc.username=postgres
spring.r2dbc.password=123

# Inicializaci�n autom�tica del esquema (opcional si usas docker-entrypoint)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.r2dbc.pool.enabled=true
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG
